version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - ./data/shared:/data/shared  # Ruta genérica relativa a la ubicación del docker-compose.yml
    restart: unless-stopped

volumes:
  mongodata:
    driver: local
