version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
      - "C:/Users/ebrav/Documents/Inacap/2024 -01/Bases De Datos No Estructuradas/Clase04:/data/shared"  
    restart: unless-stopped

volumes:
  mongodata:
    driver: local
